% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Cours 7 ACT3035},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Cours 7 ACT3035}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

Ceci est un cours pour introduire les concepts et syntaxe du R Markdow
avec un exemple concret de régression linéaire. Le matériel nécessaire
pour la syntaxe se trouve dans
\href{https://nmeraihi.github.io/act3035book/sommaire.html}{ACT3035}.

Pour débuter avec cet exemple concret, allons chercher les donnes
\texttt{flight\_delay.csv} dans le repo
\href{https://github.com/nmeraihi/ACT3035/tree/master/HIV_2024}{ACT3035H24}.

\hypertarget{ecploration-des-donnuxe9es}{%
\subsection{Ecploration des données}\label{ecploration-des-donnuxe9es}}

Nous allons essayer de prédire les retards d'avions en appliquant une
régression lin multiple sur les données \texttt{flight\_delay.csv}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data1 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/nmeraihi/ACT3035/master/HIV\_2024/flight\_delay.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Rgegardons ensuite les première observations des ces données

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Carrier Airport_Distance Number_of_flights Weather Support_Crew_Available
## 1      UA              437             41300       5                     83
## 2      UA              451             41516       5                     82
## 3      AA              425             37404       5                    175
## 4      B6              454             44798       6                     49
## 5      DL              455             40643       6                     55
## 6      UA              416             39707       5                    146
##   Baggage_loading_time Late_Arrival_o Cleaning_o Fueling_o Security_o Arr_Delay
## 1                   17             19         15        26         31        58
## 2                   17             19         15        22         32        48
## 3                   16             17         14        28         29        16
## 4                   18             19         13        29         31        81
## 5                   17             19         18        26         37        62
## 6                   16             19          6        28         31        34
\end{verbatim}

Maintenant regardons quelles sont les dimensions de ce jeux de données:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3593   11
\end{verbatim}

affichons les statistiques descriptives de la variable réponse
\texttt{Arr\_Delay}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(data1}\SpecialCharTok{$}\NormalTok{Arr\_Delay)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0    49.0    70.0    69.8    90.0   180.0
\end{verbatim}

Regardons la corrélation \textbf{Pearson} des deux variables
\texttt{Arr\_Delay} et \texttt{Number\_of\_flights}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr }\OtherTok{\textless{}{-}} \FunctionTok{cor.test}\NormalTok{(data1}\SpecialCharTok{$}\NormalTok{Arr\_Delay, data1}\SpecialCharTok{$}\NormalTok{Number\_of\_flights, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}
\NormalTok{corr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  data1$Arr_Delay and data1$Number_of_flights
## t = 86.823, df = 3591, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.8121611 0.8332786
## sample estimates:
##      cor 
## 0.823004
\end{verbatim}

On voit bien qu'il existe une forte corrélation de l'orde de 0.823 entre
nos deux variable d'intérêt Arr\_Delay\texttt{et}Number\_of\_flights`

\hypertarget{graphiques}{%
\subsection{Graphiques}\label{graphiques}}

Allons maintenant tracer quelques graphiques de type nuage de points sur
la variable dépondantes avec d'autres variable dans mon jeu de données.

\hypertarget{arr_delay-vs-number_of_flights}{%
\subsubsection{Arr\_Delay vs
Number\_of\_flights}\label{arr_delay-vs-number_of_flights}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(data1}\SpecialCharTok{$}\NormalTok{Arr\_Delay, data1}\SpecialCharTok{$}\NormalTok{Number\_of\_flights)}
\end{Highlighting}
\end{Shaded}

\includegraphics{cours7_files/figure-latex/unnamed-chunk-6-1.pdf}

\hypertarget{arr_delay-vs-security_o}{%
\subsubsection{Arr\_Delay vs
Security\_o}\label{arr_delay-vs-security_o}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Arr\_Delay, }\AttributeTok{y=}\NormalTok{Security\_o))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Retard d\textquotesingle{}arrivées vs Sécurité\_o"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{cours7_files/figure-latex/unnamed-chunk-8-1.pdf} \#\#\#
Arr\_Delay vs Support\_Crew\_Available

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Arr\_Delay, }\AttributeTok{y=}\NormalTok{Support\_Crew\_Available))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Retard d\textquotesingle{}arrivées vs Support\_Crew\_Available"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{cours7_files/figure-latex/unnamed-chunk-9-1.pdf}

\hypertarget{arr_delay-vs-airport_distance}{%
\subsubsection{Arr\_Delay vs
Airport\_Distance}\label{arr_delay-vs-airport_distance}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Arr\_Delay, }\AttributeTok{y=}\NormalTok{Airport\_Distance))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Retard d\textquotesingle{}arrivées vs Airport\_Distance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{cours7_files/figure-latex/unnamed-chunk-10-1.pdf}

\hypertarget{moduxe9liation}{%
\subsection{Modéliation}\label{moduxe9liation}}

Supprimons d'abord la première variable \texttt{Carrier} et copions je
de données dans un autre \emph{data frame} appelé \texttt{data2}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data2 }\OtherTok{\textless{}{-}}\NormalTok{ data1[}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

Regardons donc les première observations de ce jeu données:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Airport_Distance Number_of_flights Weather Support_Crew_Available
## 1              437             41300       5                     83
## 2              451             41516       5                     82
## 3              425             37404       5                    175
## 4              454             44798       6                     49
## 5              455             40643       6                     55
## 6              416             39707       5                    146
##   Baggage_loading_time Late_Arrival_o Cleaning_o Fueling_o Security_o Arr_Delay
## 1                   17             19         15        26         31        58
## 2                   17             19         15        22         32        48
## 3                   16             17         14        28         29        16
## 4                   18             19         13        29         31        81
## 5                   17             19         18        26         37        62
## 6                   16             19          6        28         31        34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dimension }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(data2)}
\end{Highlighting}
\end{Shaded}

Nous avons donc maintenant 3593 obesrvations sur 10 variables.

\hypertarget{division-des-donnuxe9es}{%
\subsubsection{Division des données}\label{division-des-donnuxe9es}}

Nous allons maintenant diviser nos données en deux parties, soient un
échantillons aléatoire afin d'ajuster le modèle de régression liné
multiples. L'autres partie restante des données, servira à tester la
performance de notre modèle.

Pour cela, nous avons besoin d'un \emph{package} appelé \texttt{caTools}

Afin de répéter cette expérience avec les mêmes résultats, nous allons
fixer notre seed à 3035.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{3035}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Faisons un tirage aléatoire de 70\% des observations de la variable
réponse \texttt{Arr\_Delay}. Cette échantillonage nous servira a diviser
toutes les données en deux partie; 70\% des données de data2 sera alloué
à entraîner le modèle. La partie restante (30\%) servira à tester le
modèle.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample }\OtherTok{\textless{}{-}}\NormalTok{ caTools}\SpecialCharTok{::}\FunctionTok{sample.split}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{Arr\_Delay, }\AttributeTok{SplitRatio =}\NormalTok{ .}\DecValTok{70}\NormalTok{)}
\NormalTok{train\_data }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data2, sample}\SpecialCharTok{==}\NormalTok{T)}
\NormalTok{test\_data }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data2, sample}\SpecialCharTok{==}\NormalTok{F)}
\end{Highlighting}
\end{Shaded}

Ajustons un premier modèle apelé \texttt{model} sur toutes les données
\texttt{train\_data}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Arr\_Delay}\SpecialCharTok{\textasciitilde{}}\NormalTok{., }\AttributeTok{data =}\NormalTok{ train\_data)}
\end{Highlighting}
\end{Shaded}

Voici un apperçu sommaire du modèle:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Arr_Delay ~ ., data = train_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -37.177  -8.390  -0.479   8.247  69.314 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)            -5.762e+02  9.039e+00 -63.752  < 2e-16 ***
## Airport_Distance        1.650e-01  1.625e-02  10.152  < 2e-16 ***
## Number_of_flights       4.480e-03  1.295e-04  34.601  < 2e-16 ***
## Weather                 5.172e+00  5.411e-01   9.559  < 2e-16 ***
## Support_Crew_Available -4.846e-02  6.382e-03  -7.594 4.36e-14 ***
## Baggage_loading_time    1.300e+01  5.238e-01  24.822  < 2e-16 ***
## Late_Arrival_o          7.113e+00  3.949e-01  18.015  < 2e-16 ***
## Cleaning_o             -2.213e-03  7.217e-02  -0.031    0.976    
## Fueling_o               3.560e-02  7.140e-02   0.499    0.618    
## Security_o              1.555e-02  3.562e-02   0.437    0.662    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 12.45 on 2504 degrees of freedom
## Multiple R-squared:  0.8195, Adjusted R-squared:  0.8188 
## F-statistic:  1263 on 9 and 2504 DF,  p-value: < 2.2e-16
\end{verbatim}

Nous remarquons que certaines variales, comme \texttt{Cleaning\_o},
\texttt{Fueling\_o} et \texttt{Security\_o} ne sont pas significatives
selon la \emph{P value}, nous allons donc les exclure du modèle
amélioré.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_amélioré }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Arr\_Delay}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airport\_Distance}\SpecialCharTok{+}\NormalTok{Number\_of\_flights}\SpecialCharTok{+}\NormalTok{Weather}\SpecialCharTok{+}\NormalTok{Support\_Crew\_Available}\SpecialCharTok{+}\NormalTok{Baggage\_loading\_time}\SpecialCharTok{+}\NormalTok{Late\_Arrival\_o, }\AttributeTok{data=}\NormalTok{train\_data)}
\end{Highlighting}
\end{Shaded}

regardons maintenant un apperçu de ce nouveau modèle:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model\_amélioré)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Arr_Delay ~ Airport_Distance + Number_of_flights + 
##     Weather + Support_Crew_Available + Baggage_loading_time + 
##     Late_Arrival_o, data = train_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -37.221  -8.410  -0.538   8.196  69.315 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)            -5.751e+02  8.782e+00 -65.484  < 2e-16 ***
## Airport_Distance        1.649e-01  1.624e-02  10.152  < 2e-16 ***
## Number_of_flights       4.478e-03  1.292e-04  34.655  < 2e-16 ***
## Weather                 5.175e+00  5.408e-01   9.569  < 2e-16 ***
## Support_Crew_Available -4.837e-02  6.372e-03  -7.591 4.43e-14 ***
## Baggage_loading_time    1.302e+01  5.225e-01  24.927  < 2e-16 ***
## Late_Arrival_o          7.114e+00  3.942e-01  18.049  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 12.44 on 2507 degrees of freedom
## Multiple R-squared:  0.8194, Adjusted R-squared:  0.819 
## F-statistic:  1896 on 6 and 2507 DF,  p-value: < 2.2e-16
\end{verbatim}

Regardons comment le modèle prédit les valeurs sur les données
d'entrainement:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_train }\OtherTok{\textless{}{-}}\NormalTok{ model\_amélioré}\SpecialCharTok{$}\NormalTok{fitted.values}
\FunctionTok{head}\NormalTok{(pred\_train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1         3         5         7         8         9 
## 60.352362  9.225622 66.907535 64.229115 47.759742 71.641443
\end{verbatim}

Regardons comment mon modèle performe sur les données cachées
(test\_data). Pour ce faire, nous allons comparer ce que nous avons
observer dans ce jeu de données avev ce qui sera prédit par le
modèle\_améioré qui a été entrainé sur les data\_train.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_test }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_amélioré, }\AttributeTok{newdata =}\NormalTok{ test\_data)}
\end{Highlighting}
\end{Shaded}

Insérons ces prédictions dans un nouveau data frame appelé
\texttt{pred\_test\_df}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_test\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(pred\_test)}
\end{Highlighting}
\end{Shaded}

Regardons les données observées de l'échantilon test vs les prédiction.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{Arr\_Delay, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(pred\_test\_df, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{cours7_files/figure-latex/unnamed-chunk-23-1.pdf}

ceci est un exemple du code Latex si on veux écrire l'infini \(\infty\)
à \(\infty\)

\hypertarget{courbe-roc}{%
\subsubsection{Courbe ROC}\label{courbe-roc}}

Comparer la performance du modèle avec la courbe ROC.

\end{document}
